services:
  apache:
    image: tugboatqa/httpd
    default: true
    commands:
      init:
        - curl -fsSL https://deb.nodesource.com/setup_20.x | bash -
        - apt-get install -y nodejs
        - mkdir -p "${DOCROOT}/chord-matrix"
      update:
        - npm ci --include=dev
      build:
        - npm run build
        - cp -r docs/* "${DOCROOT}/chord-matrix/ "

debug: true
