services:
  nginx:
    image: tugboatqa/nginx
    default: true
    commands:
      init:
        - curl -fsSL https://deb.nodesource.com/setup_20.x | bash -
        - apt-get install -y nodejs
        - npm ci --include=dev
        - mkdir "${DOCROOT}/chord-matrix"
      build:
        - npm run build
        - ln -snf "${TUGBOAT_ROOT}/docs" "${DOCROOT}/chord-matrix"
        - chown -R www-data:www-data "${DOCROOT}"
      urls:
        - /chord-matrix/

debug: true
