services:
  nginx:
    image: tugboatqa/nginx
    default: true
    commands:
      init:
        - curl -fsSL https://deb.nodesource.com/setup_20.x | bash -
        - apt-get install -y nodejs
        - npm ci --include=dev
      build:
        - npm run build
        - ln -snf "${TUGBOAT_ROOT}/docs" "${DOCROOT}"

debug: true
